plugins:
  - jest

env:
  node: true

extends:
  - "airbnb-base"

parserOptions:
  ecmaVersion: latest

rules:
  {
    no-console: 0,
    import/extensions: - error, # FIXME: remove when rule will be adjusted for new nodejs version
    - ignorePackages,
    - js: always,
    no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }],
  }
